let input = require('fs').readFileSync('/dev/stdin', 'utf8');
let valor = parseFloat(input);

console.log("NOTAS:");
let cem = Math.floor(valor / 100);
valor = valor % 100;
console.log(cem + " nota(s) de R$ 100.00");
let cinquenta = Math.floor(valor / 50);
valor = valor % 50;
console.log(cinquenta + " nota(s) de R$ 50.00");
let vinte = Math.floor(valor / 20);
valor = valor % 20;
console.log(vinte + " nota(s) de R$ 20.00");
let dez = Math.floor(valor / 10);
valor = valor % 10;
console.log(dez + " nota(s) de R$ 10.00");
let cinco = Math.floor(valor / 5);
valor = valor % 5;
console.log(cinco + " nota(s) de R$ 5.00");
let dois = Math.floor(valor / 2);
valor = valor % 2;
console.log(dois + " nota(s) de R$ 2.00");

console.log("MOEDAS:");
let um_real = Math.floor(valor / 1);
valor = valor % 1;
console.log(um_real + " moeda(s) de R$ 1.00");
valor = valor * 100;
let cinquenta_centavos = Math.floor(valor / 50);
valor = valor % 50;
console.log(cinquenta_centavos + " moeda(s) de R$ 0.50");
let vinte_e_cinco_centavos = Math.floor(valor / 25);
valor = valor % 25;
console.log(vinte_e_cinco_centavos + " moeda(s) de R$ 0.25");
let dez_centavos = Math.floor(valor / 10);
valor = valor % 10;
console.log(dez_centavos + " moeda(s) de R$ 0.10");
let cinco_centavos = Math.floor(valor / 5);
valor = valor % 5;
console.log(cinco_centavos + " moeda(s) de R$ 0.05");
let um_centavo = Math.floor(valor / 1);
valor = valor % 1;
console.log(um_centavo + " moeda(s) de R$ 0.01");